# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

steps:

# Create AKS subnet and cluster according to specs
- task: AzureCLI@2
  enabled: true
  name: "create_mgmt_vm"
  displayName: "Create VM for appdev team"
  inputs:
    azureSubscription: 'aks-infra-pipeline'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: './create.sh $(admin_resource_group) $(resource_group) $(location) $(mgmt_vnet_name) $(vm_username) $(vm_hostname) $(mgmt_subnet_name)'
    workingDirectory: 'aks-sec-demo/pipeline/2_bastion'

