apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dogvcat-ingress
  namespace: dev
spec:
  rules:
  - host: aks-itm-flink.demo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: azure-vote-front
          servicePort: 80
